export const products = [
  {
    id: 1,
    name: "Cam Sành Vĩnh Long",
    price: 35000,
    img: "https://images.unsplash.com/photo-1557800636-894a64c1696f?q=80&w=500&auto=format&fit=crop",
    desc: "Cam sành tươi, mọng nước, giàu vitamin C.",
    category: "fruit",
    unit: "kg",
    quantity: 10,
  },
  {
    id: 2,
    name: "Xoài Cát Hòa Lộc",
    price: 80000,
    img: "https://picsum.photos/500/500?random=1",
    desc: "Xoài chín cây, thơm lừng, vị ngọt thanh đặc trưng.",
    category: "fruit",
    unit: "kg",
    quantity: 5,
  },
  {
    id: 3,
    name: "Rau Muống Hữu Cơ",
    price: 15000,
    img: "https://images.unsplash.com/photo-1597362925123-77861d3fbac7?q=80&w=500&auto=format&fit=crop",
    desc: "Rau muống sạch, trồng theo tiêu chuẩn hữu cơ.",
    category: "vegetable",
    unit: "bó",
    quantity: 20,
  },
  {
    id: 4,
    name: "Dưa Hấu Long An",
    price: 25000,
    img: "https://picsum.photos/500/500?random=2",
    desc: "Dưa hấu vỏ mỏng, ruột đỏ ngọt lịm.",
    category: "fruit",
    unit: "trái",
    quantity: 8,
  },
];
